name: 💡 Feature request
description: Suggest an improvement for NuScope
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please check for an existing request before opening a new feature proposal.
  - type: textarea
    attributes:
      label: Problem to solve
      description: What are you trying to accomplish?
      placeholder: I am trying to...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe the solution you would like to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: Describe any alternatives or workarounds you considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any extra context or examples here.
    validations:
      required: false
